#ifndef DEFINES_HPP
# define DEFINES_HPP

# define MEMORY_TYPE_SIZE unsigned int
# define zo float
# define LEADING_ZEROS 1
# define ASCII_BAR_LENGTH 32
# define STEP_MS 100

# define INPUT_DECAY 0.333

# define T_PHYSICAL 1
# define T_VITAL 2
# define T_ACTION 3
# define T_MEASURE 4
# define T_BIAS 20
# define T_AXON 40

# define EXPRESSOR_THRESHOLD 1
# define EXPRESSOR_CURRENT 2
# define EXPRESSOR_ORIGINAL_THRESHOLD 3
# define EXPRESSOR_THRESHOLD_SHORT 4

# define DISPLAY_BAR 1
# define DISPLAY_CHARACTER 2
# define DISPLAY_NUMBERS 4
# define DISPLAY_DESCRIPTION 8
# define DISPLAY_ALL DISPLAY_BAR + DISPLAY_CHARACTER + DISPLAY_NUMBERS + DISPLAY_DESCRIPTION

#endif
